name: Deploy Helm Chart to EKS

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행
  workflow_dispatch: # 수동 실행 지원

jobs:
  deploy:
    runs-on: helm-deploy

    steps:
      # 1. Repository Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. Set up kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 4. Set up Helm
      - name: Setup Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # 5. Update kubeconfig for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-northeast-2 --name 

      # 6. Add Helm Repository
      - name: Add Helm Repository
        run: |
          helm repo add gitops_helmchart_deploy https://dev-library.github.io/gitops_helmchart_deploy
          helm repo update

      # 7. Deploy Helm Chart
      - name: Deploy Helm Chart to EKS
        run: |
          helm upgrade --install msa-helm gitops_helmchart_deploy/msa-helm-chart \
          -n msa-namespace --create-namespace \
          -f values.yaml
