name: EKS Deploy

on:
  push:
    branches:
      - main # Push to main branch triggers the workflow

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # Update to your region

    # Step 3: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0' # Match your EKS cluster version

    # Step 4: Authenticate with EKS cluster
    - name: Authenticate with EKS
      run: |
        aws eks update-kubeconfig --region ap-northeast-2 --name hana111Cluster

    # Step 5: Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.0

    # Step 6: Deploy db-chart to EKS
    - name: Deploy db-chart
      run: |
        helm upgrade --install db-release db-chart -f db-chart/values.yaml --namespace msa-namespace --create-namespace

    # Step 7: Deploy app-chart to EKS
    - name: Deploy app-chart
      run: |
        helm upgrade --install app-release app-chart -f app-chart/values.yaml --namespace msa-namespace

    # Step 8: Deploy common to EKS
    - name: Deploy common (Ingress Controller)
      run: |
        helm upgrade --install common-release common --namespace msa-namespace
